### PR TITLE
fix (#222): sorting object keys with not traversable values

### LINKED ISSUE #222: [BUG]: When sorting object with Date, Set (JS objects) they are vanished
Hey, I've spotted that when you use sorting on object which has values like Date, Set etc. they are vanished (they are set to {} - empty object)

Simple reproduction

```typescript
const obj = {
  a: 1,
  b: 2,
  c: new Date(),
  d: [
    {
      a: 1,
      c: 3,
      b: 2,
      z: 26,
      set: new Set([1, 2, 3]),
      date: {
        from: new Date(),
        to: new Date(),
      },
    },
  ],
}

const sortedObj = sortObject(obj);
```

result:
```
{
  "a": 1,
  "b": 2,
  "c": {},
  "d": [
    {
      "a": 1,
      "b": 2,
      "c": 3,
      "date": {
        "from": {},
        "to": {}
      },
      "set": {},
      "z": 26
    }
  ]
}
```

expected result:
```
{
  "a": 1,
  "b": 2,
  "c": "2024-04-22T09:10:57.756Z",
  "d": [
    {
      "a": 1,
      "b": 2,
      "c": 3,
      "date": {
        "from": "2024-04-22T09:10:57.756Z",
        "to": "2024-04-22T09:10:57.756Z"
      },
      "set": {},
      "z": 26
    }
  ]
}
```

### PR DESCRIPTION
**Pull request by sebslon**
fixes #222

### CODE REVIEW

**Comment by balupton** [comment]
We should check if this package is used on class instances in the wild, as this would break sorting them. Perhaps an alternative would be `Object.keys(value).length !== 0`. However, I agree your approach makes the most sense.

**Comment by sebslon** [comment]
Hey, thank you for your feedback. I see, checked and understand your concern and I agree that it breaks class instances when sorting.

`Object.keys(value).length !== 0` unfortunately also leaves pure JS objects if they have properties (`X { y: 2 }` -> `{ y: 2 }`)

**Comment by sebslon** [comment]
Hey @balupton, I've added additional handling for cases when there are class instances.

Please take a look and let me know if you see any issues ;)

Thanks again for your response!

**Comment by sebslon** [comment]
Hey @balupton any opinions on this one or should I close this PR? :)

Thanks!

**Comment by balupton** [comment]
Back to work from backpacking, give me a few weeks to catch up

**Pull request closed without merging**
